### ISSUE TITLE
[BUG] - full-body-drop werkt niet

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-upload#53]
**Omschrijf het probleem**
Wanneer het **full-body-drop** attribuut gebruikt wordt, zou de volledige browser als drop element moeten fungeren.

**Hoe te reproduceren**
Te reproduceren op de demo pagina of via onderstaande code snipper:

``` html
<vl-upload url="http://example.com" input-name="files" full-body-drop></vl-upload>
```

**Gewenst gedrag**
De volledige browser moet als drop element fungeren wanneer het **full-body-drop** attribuut gebruikt wordt.

**Screenshots**
Gedrag zoals het zou moeten, cfr. [Webuniversum](https://overheid.vlaanderen.be/webuniversum/v3/documentation/forms/vl-ui-upload).
![full-body](https://user-images.githubusercontent.com/11139249/65337003-a41f4b80-dbc7-11e9-9e24-cc56b6c53a3a.png)

**Omgeving (gelieve aan te vullen):**
 - Versie component **0.0.20**

**Comment by LucasSledsens** [comment]
Removed deprecated vl-full-body-drop property. The property didn't work since 2019, and after checking in with the teams it appeared that no one was using the property. Since there was no easy solution, and there was no demand, we decided to drop the feature. As discussed with @stefanborghys @Pieter-Beckers @SBylemans and @SanderKleykens. https://github.com/milieuinfo/webcomponent-vl-ui-upload/releases/tag/v3.7.2
