### ISSUE TITLE
[BUG] - full-body-drop attribuut verwijderen doet niets

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-upload#56]
**Omschrijf het probleem**
Wanneer initieel het full-body-drop attribuut geactiveerd werd, maar later verwijderd wordt. Zal full-body-drop nog steeds geactiveerd staan bij de vl-upload component.

**Hoe te reproduceren**
Stappen om het probleem te reproduceren en indien mogelijks een code snippet:

``` html
<vl-upload id="test" url="http://example.com" input-name="files" full-body-drop></vl-upload>
```
``` javascript
document.querySelector('#test').removeAttribute('full-body-drop');
```

**Gewenst gedrag**
Het full-body-drop moet togglebaar zijn.

**Omgeving (gelieve aan te vullen):**
 - Versie component **0.0.20**

**Comment by LucasSledsens** [comment]
Removed deprecated vl-full-body-drop property. The property didn't work since 2019, and after checking in with the teams it appeared that no one was using the property. Since there was no easy solution, and there was no demand, we decided to drop the feature. As discussed with @stefanborghys @Pieter-Beckers @SBylemans and @SanderKleykens. https://github.com/milieuinfo/webcomponent-vl-ui-upload/releases/tag/v3.7.2
